/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Cliente;
import model.DaoCliente;

/**
 *
 * @author superior
 */
public class ClienteView extends javax.swing.JFrame {
    DaoCliente daoCliente;
    Cliente cliente;
    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
        daoCliente = new DaoCliente();
        jtClientes.setModel(new ClienteTableModel(daoCliente.buscarTodos()));
        cliente = new Cliente();
        botaoExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroupOptions = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        label_codigo = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        label_idade = new javax.swing.JLabel();
        tf_idade = new javax.swing.JTextField();
        label_cpf = new javax.swing.JLabel();
        tf_cpf = new javax.swing.JTextField();
        label_telefone = new javax.swing.JLabel();
        tf_telefone = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        label_cExclusivo = new javax.swing.JLabel();
        tf_cExclusivo = new javax.swing.JTextField();
        botaoNovo = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        botaoListarTodos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbPesqNome = new javax.swing.JRadioButton();
        rbPesqEmail = new javax.swing.JRadioButton();
        rbPesqCpf = new javax.swing.JRadioButton();
        rbPesqTelefone = new javax.swing.JRadioButton();
        tfPesquisa = new javax.swing.JTextField();
        botaoFiltrar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Clientes");

        label_codigo.setText("Código:");

        label_nome.setText("Nome:");

        tf_codigo.setEditable(false);
        tf_codigo.setBackground(new java.awt.Color(179, 179, 179));

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        label_idade.setText("Idade:");

        label_cpf.setText("CPF:");

        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        label_telefone.setText("Telefone:");

        tf_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefoneActionPerformed(evt);
            }
        });

        label_email.setText("Email:");

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        label_cExclusivo.setText("Número do cartão exclusivo:");

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtClientes);

        botaoListarTodos.setText("Listar todos");
        botaoListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarTodosActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar por:");

        buttonGroupOptions.add(rbPesqNome);
        rbPesqNome.setText("Nome");
        rbPesqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPesqNomeActionPerformed(evt);
            }
        });

        buttonGroupOptions.add(rbPesqEmail);
        rbPesqEmail.setText("Email");

        buttonGroupOptions.add(rbPesqCpf);
        rbPesqCpf.setText("CPF");

        buttonGroupOptions.add(rbPesqTelefone);
        rbPesqTelefone.setText("Telefone");

        tfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaActionPerformed(evt);
            }
        });

        botaoFiltrar.setText("Filtrar");
        botaoFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoNovo)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_cExclusivo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(74, 74, 74)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(botaoSalvar)
                        .addGap(37, 37, 37)
                        .addComponent(botaoExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_email)
                                .addGap(40, 40, 40)
                                .addComponent(tf_email))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_cExclusivo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_idade)
                                    .addComponent(label_nome)
                                    .addComponent(label_codigo))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(label_cpf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(label_telefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_telefone))
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(24, 24, 24))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(rbPesqNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPesqEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPesqCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbPesqTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPesquisa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoFiltrar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoListarTodos)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_codigo)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_cpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_cpf)
                        .addComponent(tf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_telefone)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cExclusivo)
                    .addComponent(tf_cExclusivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoNovo)
                    .addComponent(botaoExcluir))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbPesqNome)
                    .addComponent(rbPesqEmail)
                    .addComponent(rbPesqCpf)
                    .addComponent(rbPesqTelefone)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoListarTodos)
                    .addComponent(botaoFiltrar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telefoneActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Confirma exclusão ?","Exclusão de cliente",JOptionPane.YES_NO_OPTION);
        
        if(confirmacao==0){
            daoCliente.excluir(Integer.parseInt(tf_codigo.getText()));
            jtClientes.setModel(new ClienteTableModel(daoCliente.buscarTodos()));
            this.limparCampos();
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if(tf_cExclusivo.getText().equals("") || tf_cpf.getText().equals("") || 
                tf_nome.getText().equals("") || tf_email.getText().equals("")
                || tf_telefone.getText().equals("") || tf_idade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "É mecessário preencher todos os campos", "Aviso",JOptionPane.WARNING_MESSAGE);
        } else {
            cliente.setNome(tf_nome.getText());
            cliente.setCPF(tf_cpf.getText());
            cliente.setIdade(Integer.parseInt(tf_idade.getText()));
            cliente.setEmail(tf_email.getText());
            cliente.setCartaoExclusivo(Integer.parseInt(tf_cExclusivo.getText()));
            cliente.setTelefone(tf_telefone.getText());
            
            if(tf_codigo.getText().trim().equals("")){
                daoCliente.inserir(cliente);
            } else {
                cliente.setCodigo(Integer.parseInt(tf_codigo.getText()));
                daoCliente.alterar(cliente);
            }
            jtClientes.setModel(new ClienteTableModel(daoCliente.buscarTodos()));
            this.limparCampos();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked
        tf_codigo.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_CODIGO).toString());
        tf_nome.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_NOME).toString());
        tf_cExclusivo.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_CARTAO_EXCLUSIVO).toString());
        tf_cpf.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_CPF).toString());
        tf_email.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_EMAIL).toString());
        tf_telefone.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(),ClienteTableModel.COL_TELEFONE).toString());
        tf_idade.setText(jtClientes.getValueAt(jtClientes.getSelectedRow(), ClienteTableModel.COL_IDADE).toString());
        botaoExcluir.setEnabled(true);
    }//GEN-LAST:event_jtClientesMouseClicked

    private void rbPesqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPesqNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPesqNomeActionPerformed

    private void tfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaActionPerformed

    private void botaoFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFiltrarActionPerformed
        String campo;
        System.out.println("HEY !");
        if(rbPesqNome.isSelected()){
            campo = "nome";
        }else if(rbPesqEmail.isSelected()){
            campo = "email";
        } else if(rbPesqTelefone.isSelected()){
            campo = "telefone";
        } else {
            campo = "cpf";
        }
        jtClientes.setModel(new ClienteTableModel(daoCliente.buscarPorFiltro(campo, tfPesquisa.getText())));
        this.limparCampos();
    }//GEN-LAST:event_botaoFiltrarActionPerformed

    private void botaoListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarTodosActionPerformed
        jtClientes.setModel(new ClienteTableModel(daoCliente.buscarTodos()));
        this.limparCampos();
        
    }//GEN-LAST:event_botaoListarTodosActionPerformed
    
    /**
     * @param args the command line arguments
     */
     public void limparCampos() {
        tf_cExclusivo.setText("");
        tf_cpf.setText("");
        tf_email.setText("");
        tf_nome.setText("");
        tf_telefone.setText("");
        tf_idade.setText("");
        tf_codigo.setText("");
        botaoExcluir.setEnabled(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoFiltrar;
    private javax.swing.JButton botaoListarTodos;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupOptions;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtClientes;
    private javax.swing.JLabel label_cExclusivo;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_idade;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JRadioButton rbPesqCpf;
    private javax.swing.JRadioButton rbPesqEmail;
    private javax.swing.JRadioButton rbPesqNome;
    private javax.swing.JRadioButton rbPesqTelefone;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tf_cExclusivo;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_cpf;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_idade;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_telefone;
    // End of variables declaration//GEN-END:variables
}
